version: '3'

services:
  app:
    build: .
    depends_on:
      - mongo-local
    networks:
      - integ
    ports:
      - 8080:8080
    environment:
      - MONGO_URI=mongodb://productListUser:productListPassword@mongo-local:27017/promotions?authSource=admin
  mongo-local:
    container_name: mongodb-local # this allow to import the data
    image: mongo:3.6.8
    ports:
      - 27017:27017
    networks:
      - integ
    environment:
      - MONGO_INITDB_ROOT_USERNAME=productListUser
      - MONGO_INITDB_ROOT_PASSWORD=productListPassword
    volumes:
      - ./products-db/database:/database
networks:
  integ:
    driver: bridge